### ISSUE TITLE
👾 BUG | error: Trailing spaces not allowed

### ISSUE THREAD

**Issue by GouDanYuan** [d2-projects/d2-admin#188]
```
error: Trailing spaces not allowed (no-trailing-spaces) at src\views\system\login\page.vue:94:70:
  92 |           </p>
  93 |           <p class="page-login--content-footer-copyright">
> 94 |             {{ $t('views.system.login.footer.copyright.copyright') }}
     |                                                                      ^
  95 |             <d2-icon name="copyright"/>
  96 |             {{ $t('views.system.login.footer.copyright.content') }}
  97 |             <a href="https://github.com/FairyEver">


error: Trailing spaces not allowed (no-trailing-spaces) at src\views\system\login\page.vue:95:40:
  93 |           <p class="page-login--content-footer-copyright">
  94 |             {{ $t('views.system.login.footer.copyright.copyright') }}
> 95 |             <d2-icon name="copyright"/>
     |                                        ^
  96 |             {{ $t('views.system.login.footer.copyright.content') }}
  97 |             <a href="https://github.com/FairyEver">
  98 |               @{{ $t('views.system.login.footer.copyright.author') }}


error: Trailing spaces not allowed (no-trailing-spaces) at src\views\system\login\page.vue:96:68:
  94 |             {{ $t('views.system.login.footer.copyright.copyright') }}
  95 |             <d2-icon name="copyright"/>
> 96 |             {{ $t('views.system.login.footer.copyright.content') }}
     |                                                                    ^
  97 |             <a href="https://github.com/FairyEver">
  98 |               @{{ $t('views.system.login.footer.copyright.author') }}
  99 |             </a>
```

**Comment by FairyEver** [comment]
已经修复
