### ISSUE TITLE
👾 BUG | 更换主题颜色报错且无法更换

### ISSUE THREAD

**Issue by FETE-CH** [d2-projects/d2-admin#254]
线上预览和本地开发环境都报错！

复现：

打开 `cdn.d2.pub/d2-admin/preview `，点击右上角颜色按钮，选择颜色后报错。

**Comment by FairyEver** [comment]
因为以前的颜色更新插件是需要导入 element 的 css 实现的，D2Admin 1.8.0 之后 element 样式改为了 cdn 加载，这个功能就不能继续使用了。建议删除，或者放弃在生产环境使用 cdn 加载 element

**Comment by FairyEver** [comment]
删除 https://github.com/d2-projects/d2-admin/blob/e8a231fb60198aa23af01f91320751ea82dfdd69/dependencies-cdn.js#L8 即可放弃在生产环境使用 cdn 加载 element

**Comment by hank-cp** [comment]
Same issue here.

这边经过调试发现好像是 https://github.com/d2-projects/d2-admin/commit/090f70e5ee1074ad4fa0232212da596818a170fd 引起的. 打开页面报错:

```
withCredentials.js?78e6:7 Uncaught (in promise) DOMException: Failed to set the 'responseType' property on 'XMLHttpRequest': The response type cannot be changed for synchronous requests made from a document.
    at MockXMLHttpRequest.__webpack_exports__.default.Mock.XHR.send (webpack-internal:///./src/d2admin/mock/d2-mock/patch/withCredentials.js:9:36)
    at Object.getCSSString (webpack-internal:///./node_modules/webpack-theme-color-replacer/client/themeColorChanger.js:105:13)
    at getCssText (webpack-internal:///./node_modules/webpack-theme-color-replacer/client/themeColorChanger.js:58:23)
    at eval (webpack-internal:///./node_modules/webpack-theme-color-replacer/client/themeColorChanger.js:27:17)
    at new Promise (<anonymous>)
    at Object.changeColor (webpack-internal:///./node_modules/webpack-theme-color-replacer/client/themeColorChanger.js:23:16)
    at Store.apply (webpack-internal:///./src/d2admin/store/modules/color.js:153:90)
    at wrappedMutationHandler (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:748:13)
    at commitIterator (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:400:7)
    at Array.forEach (<anonymous>)
```

注释掉d2-mock/patch/withCredentials.js后
```
    // this.custom.xhr.responseType = this.responseType
```
后功能正常

**Comment by FETE-CH** [comment]
> Same issue here.
> 
> 这边经过调试发现好像是 [090f70e](https://github.com/d2-projects/d2-admin/commit/090f70e5ee1074ad4fa0232212da596818a170fd) 引起的. 打开页面报错:
> 
> ```
> withCredentials.js?78e6:7 Uncaught (in promise) DOMException: Failed to set the 'responseType' property on 'XMLHttpRequest': The response type cannot be changed for synchronous requests made from a document.
>     at MockXMLHttpRequest.__webpack_exports__.default.Mock.XHR.send (webpack-internal:///./src/d2admin/mock/d2-mock/patch/withCredentials.js:9:36)
>     at Object.getCSSString (webpack-internal:///./node_modules/webpack-theme-color-replacer/client/themeColorChanger.js:105:13)
>     at getCssText (webpack-internal:///./node_modules/webpack-theme-color-replacer/client/themeColorChanger.js:58:23)
>     at eval (webpack-internal:///./node_modules/webpack-theme-color-replacer/client/themeColorChanger.js:27:17)
>     at new Promise (<anonymous>)
>     at Object.changeColor (webpack-internal:///./node_modules/webpack-theme-color-replacer/client/themeColorChanger.js:23:16)
>     at Store.apply (webpack-internal:///./src/d2admin/store/modules/color.js:153:90)
>     at wrappedMutationHandler (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:748:13)
>     at commitIterator (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:400:7)
>     at Array.forEach (<anonymous>)
> ```
> 
> 注释掉d2-mock/patch/withCredentials.js后
> 
> ```
>     // this.custom.xhr.responseType = this.responseType
> ```
> 
> 后功能正常

确实是这个问题，已可正常使用

**Comment by FairyEver** [comment]
thanks @hank-cp
