### ISSUE TITLE
👾 BUG | 本地run serve有warning,系统无法访问

### ISSUE THREAD

**Issue by sakula92** [d2-projects/d2-admin#274]
WARNING  Compiled with 1 warnings                                                                                                                               14:03:31
 warning  in ./src/views/demo/playground/add-routes/routes.vue

Module build failed (from ./node_modules/_eslint-loader@2.2.1@eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
Occurred while linting D:\workspace2020\vue2020\d2-admin\src\views\demo\playground\add-routes\routes.vue:69
    at SourceCode.getTokenBefore (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\token-store\index.js:303:18)
    at checkSpacingBefore (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\rules\template-curly-spacing.js:60:42)
    at TemplateElement (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\rules\template-curly-spacing.js:119:17)
    at listeners.(anonymous function).forEach.listener (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\linter.js:752:32)
    at Array.forEach (<anonymous>)
    at runRules (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\linter.js:747:15)
    at Linter._verifyWithoutProcessors (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\linter.js:899:31)
    at preprocess.map.textBlock (D:\workspace2020\vue2020\d2-admin\node_modules\_eslint@5.16.0@eslint\lib\linter.js:955:35)
    at Array.map (<anonymous>)

 @ ./src/views sync ^\.\/.*$
 @ ./src/libs/util.import.development.js
 @ ./src/router/routes.js
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@3.10.3@webpack-dev-server/client?http://192.168.0.180:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js @/mock      

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.0.180:8080/

**Comment by Aysnine** [comment]
这是 babel-eslint 的一些bug，参考 https://github.com/babel/babel-eslint/issues/530 修改方法有这些：
1、升级 babel-selint
