### ISSUE TITLE
？？

### ISSUE THREAD

**Issue by gaoxinxiao** [d2-projects/d2-admin#58]
connect ETIMEDOUT 104.16.20.35:80
Error: connect ETIMEDOUT 104.16.20.35:80
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

**Comment by namklaw** [comment]
这貌似是架设服务器端报的错误吧？和这个项目本身没有什么关系呀……

**Comment by FairyEver** [comment]
网络原因，和 D2 没有关系
